language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t sjegadison/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sjegadison/docker-react npm run test




