language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t sjegadison/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sjegadison/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app:  "docker-react-sj"
  env:  "DockerReactSj-env"
  bucket-name:  "elasticbeanstalk-us-east-2-748645781037"
  bucket-path:  "docker-react-sj"
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  on:
    branch: master



